
#ifndef LV_DRV_CONF_H
#define LV_DRV_CONF_H

#define CONFIG_LVGL_DISPLAY_WIDTH 480
#define CONFIG_LVGL_DISPLAY_HEIGHT 320
#define CONFIG_LVGL_TFT_DISPLAY_CONTROLLER_ST7789 true

#define CONFIG_LV_HOR_RES_MAX CONFIG_LVGL_DISPLAY_WIDTH
#define CONFIG_LV_VER_RES_MAX CONFIG_LVGL_DISPLAY_HEIGHT
// size of lv_color_t
// should be greater than 1/10 whole screen.
#define LV_DRAW_BUFFER_SIZE (CONFIG_LVGL_DISPLAY_WIDTH * CONFIG_LVGL_DISPLAY_HEIGHT /4)


#endif