// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: S320240

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_screenMain
void ui_screenMain_screen_init(void);
void ui_event_screenMain( lv_event_t * e);
lv_obj_t *ui_screenMain;
lv_obj_t *ui_lbMode;
lv_obj_t *ui_lbState;
lv_obj_t *ui_lbStatusTime;
lv_obj_t *ui_lbBeer;
lv_obj_t *ui_lbBeerSet;
lv_obj_t *ui_lbRoom;
lv_obj_t *ui_lbFridge;
lv_obj_t *ui_lbFridgeSet;
lv_obj_t *ui_lbPressure;
lv_obj_t *ui_lbDegree;
lv_obj_t *ui_lbGravity;
lv_obj_t *ui_lbISpindelTemp;
lv_obj_t *ui_lbAngle;
lv_obj_t *ui_lbISpindelBat;
lv_obj_t *ui_lbOg;
lv_obj_t *ui_lbAbv;
lv_obj_t *ui_lbAtt;
lv_obj_t *ui_lbUpdate;
lv_obj_t *ui_lbRssi;
lv_obj_t *ui_lbWirelessHydrometer;

//#if	EanbleParasiteTempControl
lv_obj_t *ui_lbGlycolTemperature;
lv_obj_t *ui_lbGlycolTempSet;
lv_obj_t *ui_lbGlycolState;
lv_obj_t *ui_lbGlycolElapsedTime;
//#endif
#if EnableHumidityControlSupport
lv_obj_t *ui_lbHumidityControlState;
lv_obj_t *ui_lbRoomHumidity;
lv_obj_t *ui_lbChamberHumidity;
lv_obj_t *ui_lbTargetHumidity;
#endif

void ui_event_btnSetting( lv_event_t * e);
lv_obj_t *ui_btnSetting;
void ui_event_btnControl( lv_event_t * e);
lv_obj_t *ui_btnControl;
void ui_event_btnGravity( lv_event_t * e);
lv_obj_t *ui_btnGravity;
void ui_event_btnOriginalGravity( lv_event_t * e);
lv_obj_t *ui_btnOriginalGravity;


// SCREEN: ui_screenTempControl
void ui_screenTempControl_screen_init(void);
void ui_event_screenTempControl( lv_event_t * e);
lv_obj_t *ui_screenTempControl;
void ui_event_btnTempControlBack( lv_event_t * e);
lv_obj_t *ui_btnTempControlBack;
void ui_event_sldMode( lv_event_t * e);
lv_obj_t *ui_sldMode;
void ui_event_arcTemperatureSet( lv_event_t * e);
lv_obj_t *ui_arcTemperatureSet;
lv_obj_t *ui_lbMinTempSet;
lv_obj_t *ui_lbMaxTempSet;
lv_obj_t *ui_lbTemperatureSet;
lv_obj_t *ui_lbControlUnit;
lv_obj_t *ui_Image1;


// SCREEN: ui_screenSetting
void ui_screenSetting_screen_init(void);
void ui_event_screenSetting( lv_event_t * e);
lv_obj_t *ui_screenSetting;
void ui_event_btnSettingBack( lv_event_t * e);
lv_obj_t *ui_btnSettingBack;
void ui_event_swWiFi( lv_event_t * e);
lv_obj_t *ui_swWiFi;
lv_obj_t *ui_lbNetwork;
lv_obj_t *ui_lbAddress;
void ui_event_swApMode( lv_event_t * e);
lv_obj_t *ui_swApMode;
lv_obj_t *ui_lbHostname;
lv_obj_t *ui_lbUsername;
lv_obj_t *ui_lbPasswd;
void ui_event_btnSearchNetwork( lv_event_t * e);
lv_obj_t *ui_btnSearchNetwork;
lv_obj_t *ui_Image2;


// SCREEN: ui_screenInput
void ui_screenInput_screen_init(void);
lv_obj_t *ui_screenInput;
void ui_event_kbInput( lv_event_t * e);
lv_obj_t *ui_kbInput;
lv_obj_t *ui_lbInputLabel;
lv_obj_t *ui_taInput;
lv_obj_t *ui____initial_actions0;
//const lv_img_dsc_t *ui_imgset_cotrol__5[1] = {&ui_img_cotrol_3_5_png};
//const lv_img_dsc_t *ui_imgset_main_5[1] = {&ui_img_main3_5_png};
const lv_img_dsc_t *ui_imgset_1797070980[1] = {&ui_img_203665058};
//const lv_img_dsc_t *ui_imgset_setting__5[1] = {&ui_img_setting_3_5_png};
const lv_img_dsc_t *ui_imgset_control_[1] = {&ui_img_control_320240_png};
//const lv_img_dsc_t *ui_imgset_main_[1] = {&ui_img_main_320240_png};
const lv_img_dsc_t *ui_imgset_setting_[1] = {&ui_img_setting_320240_png};
const lv_img_dsc_t *ui_imgset_main_3040v[1] = {&ui_img_main_320240v2_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_screenMain( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SCREEN_LOAD_START) {
      onMainScreenLoadStart( e );
}
if ( event_code == LV_EVENT_SCREEN_UNLOAD_START) {
      onMainScreenHidden( e );
}
}
void ui_event_btnSetting( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_screenSetting, LV_SCR_LOAD_ANIM_MOVE_LEFT, 300, 0, &ui_screenSetting_screen_init);
}
}
void ui_event_btnControl( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_screenTempControl, LV_SCR_LOAD_ANIM_MOVE_LEFT, 300, 0, &ui_screenTempControl_screen_init);
}
}
void ui_event_btnGravity( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      openEditGravity( e );
}
}
void ui_event_btnOriginalGravity( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      openEditOriginalGravity( e );
}
}
void ui_event_screenTempControl( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SCREEN_LOAD_START) {
      onScreenTempControlLoadStart( e );
}
}
void ui_event_btnTempControlBack( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_screenMain, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 300, 0, &ui_screenMain_screen_init);
}
}
void ui_event_sldMode( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_RELEASED) {
      onModeChanged( e );
}
}
void ui_event_arcTemperatureSet( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_RELEASED) {
      onTemperatureSetDone( e );
}
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_arc_set_text_value( ui_lbTemperatureSet, target, "", "");
}
}
void ui_event_screenSetting( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SCREEN_LOAD_START) {
      onScreenSettingLoadStart( e );
}
}
void ui_event_btnSettingBack( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_screenMain, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 300, 0, &ui_screenMain_screen_init);
}
}
void ui_event_swWiFi( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      onWiFiStaModeChange( e );
}
}
void ui_event_swApMode( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      onWiFiApModeChange( e );
}
}
void ui_event_btnSearchNetwork( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      onSearchNetworkClicked( e );
}
}
void ui_event_kbInput( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_READY) {
      onKeyboardReadyPressed( e );
}
if ( event_code == LV_EVENT_CANCEL) {
      onKeyboardCancel( e );
}
if ( event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_ENTER  ) {
      onInputEnter( e );
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_screenMain_screen_init();
ui_screenTempControl_screen_init();
ui_screenSetting_screen_init();
ui_screenInput_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_screenMain);
}
