// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: S320240

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void onMainScreenLoadStart(lv_event_t * e);
void onMainScreenHidden(lv_event_t * e);
void openEditGravity(lv_event_t * e);
void openEditOriginalGravity(lv_event_t * e);
void onScreenTempControlLoadStart(lv_event_t * e);
void onModeChanged(lv_event_t * e);
void onTemperatureSetDone(lv_event_t * e);
void onScreenSettingLoadStart(lv_event_t * e);
void onWiFiStaModeChange(lv_event_t * e);
void onWiFiApModeChange(lv_event_t * e);
void onSearchNetworkClicked(lv_event_t * e);
void onKeyboardReadyPressed(lv_event_t * e);
void onKeyboardCancel(lv_event_t * e);
void onInputEnter(lv_event_t * e);

void onTempControlScreenClicked(lv_event_t * e);
#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
