// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: S320240

#include "../ui.h"

void ui_screenSetting_screen_init(void)
{
ui_screenSetting = lv_obj_create(NULL);
lv_obj_clear_flag( ui_screenSetting, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
if(setting_screen_background) lv_obj_set_style_bg_img_src( ui_screenSetting, setting_screen_background, LV_PART_MAIN | LV_STATE_DEFAULT );
else lv_obj_set_style_bg_img_src( ui_screenSetting, &ui_img_setting_320240_png, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_btnSettingBack = lv_imgbtn_create(ui_screenSetting);
lv_imgbtn_set_src(ui_btnSettingBack, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_backbutton_png, NULL);
lv_obj_set_width( ui_btnSettingBack, 20);
lv_obj_set_height( ui_btnSettingBack, 36);

ui_swWiFi = lv_switch_create(ui_screenSetting);
lv_obj_set_width( ui_swWiFi, 50);
lv_obj_set_height( ui_swWiFi, 25);
lv_obj_set_x( ui_swWiFi, 170 );
lv_obj_set_y( ui_swWiFi, 30 );


ui_lbNetwork = lv_label_create(ui_screenSetting);
lv_obj_set_width( ui_lbNetwork, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lbNetwork, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lbNetwork, 170 );
lv_obj_set_y( ui_lbNetwork, 68 );
lv_label_set_text(ui_lbNetwork,"Network");

ui_lbAddress = lv_label_create(ui_screenSetting);
lv_obj_set_width( ui_lbAddress, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lbAddress, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lbAddress, 170 );
lv_obj_set_y( ui_lbAddress, 96 );
lv_label_set_text(ui_lbAddress,"0.0.0.0");

ui_swApMode = lv_switch_create(ui_screenSetting);
lv_obj_set_width( ui_swApMode, 50);
lv_obj_set_height( ui_swApMode, 25);
lv_obj_set_x( ui_swApMode, 172 );
lv_obj_set_y( ui_swApMode, 122 );


ui_lbHostname = lv_label_create(ui_screenSetting);
lv_obj_set_width( ui_lbHostname, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lbHostname, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lbHostname, 170 );
lv_obj_set_y( ui_lbHostname, 158 );
lv_label_set_text(ui_lbHostname,"brewpiless");

ui_lbUsername = lv_label_create(ui_screenSetting);
lv_obj_set_width( ui_lbUsername, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lbUsername, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lbUsername, 170 );
lv_obj_set_y( ui_lbUsername, 184 );
lv_label_set_text(ui_lbUsername,"username");

ui_lbPasswd = lv_label_create(ui_screenSetting);
lv_obj_set_width( ui_lbPasswd, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lbPasswd, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lbPasswd, 170 );
lv_obj_set_y( ui_lbPasswd, 208 );
lv_label_set_text(ui_lbPasswd,"password");

ui_btnSearchNetwork = lv_imgbtn_create(ui_screenSetting);
lv_imgbtn_set_src(ui_btnSearchNetwork, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_203665058, NULL);
lv_obj_set_width( ui_btnSearchNetwork, 32);
lv_obj_set_height( ui_btnSearchNetwork, 32);
lv_obj_set_x( ui_btnSearchNetwork, 134 );
lv_obj_set_y( ui_btnSearchNetwork, -43 );
lv_obj_set_align( ui_btnSearchNetwork, LV_ALIGN_CENTER );

lv_obj_add_event_cb(ui_btnSettingBack, ui_event_btnSettingBack, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_swWiFi, ui_event_swWiFi, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_swApMode, ui_event_swApMode, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_btnSearchNetwork, ui_event_btnSearchNetwork, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_screenSetting, ui_event_screenSetting, LV_EVENT_ALL, NULL);

}
