// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: S320240

#include "../ui.h"
#if SKINNABLE
void ui_screenMain_screen_init_codegen(void)
#else
void ui_screenMain_screen_init(void)
#endif
{
ui_screenMain = lv_obj_create(NULL);
lv_obj_clear_flag( ui_screenMain, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_img_src( ui_screenMain, &ui_img_main_320240v2_png, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_lbMode = lv_label_create(ui_screenMain);
lv_obj_set_width( ui_lbMode, 100);
lv_obj_set_height( ui_lbMode, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_lbMode,"Beer Const.");

ui_lbState = lv_label_create(ui_screenMain);
lv_obj_set_width( ui_lbState, 114);
lv_obj_set_height( ui_lbState, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lbState, 102 );
lv_obj_set_y( ui_lbState, 0 );
lv_label_set_text(ui_lbState,"Cooling for");
lv_obj_set_style_text_align(ui_lbState, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lbStatusTime = lv_label_create(ui_screenMain);
lv_obj_set_width( ui_lbStatusTime, 80);
lv_obj_set_height( ui_lbStatusTime, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lbStatusTime, 220 );
lv_obj_set_y( ui_lbStatusTime, 0 );
lv_label_set_text(ui_lbStatusTime,"01h59m32s");

ui_lbBeer = lv_label_create(ui_screenMain);
lv_obj_set_width( ui_lbBeer, 80);
lv_obj_set_height( ui_lbBeer, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lbBeer, 4 );
lv_obj_set_y( ui_lbBeer, 44 );
lv_label_set_text(ui_lbBeer,"22.2");
lv_obj_set_style_text_color(ui_lbBeer, lv_color_hex(0x03EE03), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lbBeer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_lbBeer, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lbBeer, &lv_font_montserrat_32, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lbBeerSet = lv_label_create(ui_screenMain);
lv_obj_set_width( ui_lbBeerSet, 80);
lv_obj_set_height( ui_lbBeerSet, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lbBeerSet, 112 );
lv_obj_set_y( ui_lbBeerSet, 44 );
lv_label_set_text(ui_lbBeerSet,"22.2");
lv_obj_set_style_text_color(ui_lbBeerSet, lv_color_hex(0xFF3333), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lbBeerSet, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_lbBeerSet, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lbBeerSet, &lv_font_montserrat_32, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lbRoom = lv_label_create(ui_screenMain);
lv_obj_set_width( ui_lbRoom, 80);
lv_obj_set_height( ui_lbRoom, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lbRoom, 212 );
lv_obj_set_y( ui_lbRoom, 44 );
lv_label_set_text(ui_lbRoom,"22.2");
lv_obj_set_style_text_color(ui_lbRoom, lv_color_hex(0x00AAAA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lbRoom, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_lbRoom, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lbRoom, &lv_font_montserrat_32, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lbFridge = lv_label_create(ui_screenMain);
lv_obj_set_width( ui_lbFridge, 80);
lv_obj_set_height( ui_lbFridge, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lbFridge, 4 );
lv_obj_set_y( ui_lbFridge, 96 );
lv_label_set_text(ui_lbFridge,"33.3");
lv_obj_set_style_text_color(ui_lbFridge, lv_color_hex(0x03EE03), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lbFridge, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_lbFridge, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lbFridge, &lv_font_montserrat_32, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lbFridgeSet = lv_label_create(ui_screenMain);
lv_obj_set_width( ui_lbFridgeSet, 80);
lv_obj_set_height( ui_lbFridgeSet, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lbFridgeSet, 112 );
lv_obj_set_y( ui_lbFridgeSet, 96 );
lv_label_set_text(ui_lbFridgeSet,"3.0");
lv_obj_set_style_text_color(ui_lbFridgeSet, lv_color_hex(0xFF3333), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lbFridgeSet, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_lbFridgeSet, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lbFridgeSet, &lv_font_montserrat_32, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lbPressure = lv_label_create(ui_screenMain);
lv_obj_set_width( ui_lbPressure, 80);
lv_obj_set_height( ui_lbPressure, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lbPressure, 212 );
lv_obj_set_y( ui_lbPressure, 96 );
lv_label_set_text(ui_lbPressure,"22.2");
lv_obj_set_style_text_color(ui_lbPressure, lv_color_hex(0x00AAAA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lbPressure, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_lbPressure, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lbPressure, &lv_font_montserrat_32, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lbDegree = lv_label_create(ui_screenMain);
lv_obj_set_width( ui_lbDegree, 20);
lv_obj_set_height( ui_lbDegree, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lbDegree, 296 );
lv_obj_set_y( ui_lbDegree, 58 );
lv_label_set_text(ui_lbDegree,"°C");

ui_lbGravity = lv_label_create(ui_screenMain);
lv_obj_set_width( ui_lbGravity, 100);
lv_obj_set_height( ui_lbGravity, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lbGravity, 208 );
lv_obj_set_y( ui_lbGravity, 196 );
lv_label_set_text(ui_lbGravity,"1.0143");
lv_obj_set_style_text_color(ui_lbGravity, lv_color_hex(0x03EE03), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lbGravity, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_lbGravity, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lbGravity, &lv_font_montserrat_32, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lbISpindelTemp = lv_label_create(ui_screenMain);
lv_obj_set_width( ui_lbISpindelTemp, 42);
lv_obj_set_height( ui_lbISpindelTemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lbISpindelTemp, 64 );
lv_obj_set_y( ui_lbISpindelTemp, 172 );
lv_label_set_text(ui_lbISpindelTemp,"22.3");

ui_lbAngle = lv_label_create(ui_screenMain);
lv_obj_set_width( ui_lbAngle, 42);
lv_obj_set_height( ui_lbAngle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lbAngle, 64 );
lv_obj_set_y( ui_lbAngle, 194 );
lv_label_set_text(ui_lbAngle,"17.32");

ui_lbISpindelBat = lv_label_create(ui_screenMain);
lv_obj_set_width( ui_lbISpindelBat, 42);
lv_obj_set_height( ui_lbISpindelBat, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lbISpindelBat, 64 );
lv_obj_set_y( ui_lbISpindelBat, 220 );
lv_label_set_text(ui_lbISpindelBat,"4.2V");

ui_lbOg = lv_label_create(ui_screenMain);
lv_obj_set_width( ui_lbOg, 42);
lv_obj_set_height( ui_lbOg, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lbOg, 164 );
lv_obj_set_y( ui_lbOg, 172 );
lv_label_set_text(ui_lbOg,"1.076");
lv_obj_set_style_text_align(ui_lbOg, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lbAbv = lv_label_create(ui_screenMain);
lv_obj_set_width( ui_lbAbv, 42);
lv_obj_set_height( ui_lbAbv, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lbAbv, 164 );
lv_obj_set_y( ui_lbAbv, 194 );
lv_label_set_text(ui_lbAbv,"10.5%");
lv_obj_set_style_text_align(ui_lbAbv, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lbAtt = lv_label_create(ui_screenMain);
lv_obj_set_width( ui_lbAtt, 42);
lv_obj_set_height( ui_lbAtt, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lbAtt, 164 );
lv_obj_set_y( ui_lbAtt, 220 );
lv_label_set_text(ui_lbAtt,"80.5%");
lv_obj_set_style_text_align(ui_lbAtt, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lbUpdate = lv_label_create(ui_screenMain);
lv_obj_set_width( ui_lbUpdate, 80);
lv_obj_set_height( ui_lbUpdate, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lbUpdate, 64 );
lv_obj_set_y( ui_lbUpdate, 148 );
lv_label_set_text(ui_lbUpdate,"10/31 20:59");

ui_lbRssi = lv_label_create(ui_screenMain);
lv_obj_set_width( ui_lbRssi, 36);
lv_obj_set_height( ui_lbRssi, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lbRssi, 200 );
lv_obj_set_y( ui_lbRssi, 148 );
lv_label_set_text(ui_lbRssi,"-67");

ui_btnSetting = lv_btn_create(ui_screenMain);
lv_obj_set_width( ui_btnSetting, 100);
lv_obj_set_height( ui_btnSetting, 50);
lv_obj_set_align( ui_btnSetting, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( ui_btnSetting, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btnSetting, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_btnSetting, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_btnSetting, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_btnControl = lv_btn_create(ui_screenMain);
lv_obj_set_width( ui_btnControl, 200);
lv_obj_set_height( ui_btnControl, 120);
lv_obj_add_flag( ui_btnControl, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btnControl, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_btnControl, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_btnControl, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_clear_state(ui_btnControl,LV_STATE_FOCUS_KEY | LV_STATE_FOCUSED);

ui_btnGravity = lv_btn_create(ui_screenMain);
lv_obj_set_width( ui_btnGravity, 100);
lv_obj_set_height( ui_btnGravity, 80);
lv_obj_set_align( ui_btnGravity, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_add_flag( ui_btnGravity, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btnGravity, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_btnGravity, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_btnGravity, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_clear_state(ui_btnGravity,LV_STATE_FOCUS_KEY | LV_STATE_FOCUSED);

ui_btnOriginalGravity = lv_btn_create(ui_screenMain);
lv_obj_set_width( ui_btnOriginalGravity, 100);
lv_obj_set_height( ui_btnOriginalGravity, 80);
lv_obj_set_x( ui_btnOriginalGravity, -100 );
lv_obj_set_y( ui_btnOriginalGravity, 0 );
lv_obj_set_align( ui_btnOriginalGravity, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_add_flag( ui_btnOriginalGravity, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btnOriginalGravity, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_btnOriginalGravity, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_btnOriginalGravity, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_clear_state(ui_btnOriginalGravity,LV_STATE_FOCUS_KEY | LV_STATE_FOCUSED);

lv_obj_add_event_cb(ui_btnSetting, ui_event_btnSetting, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_btnControl, ui_event_btnControl, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_btnGravity, ui_event_btnGravity, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_btnOriginalGravity, ui_event_btnOriginalGravity, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_screenMain, ui_event_screenMain, LV_EVENT_ALL, NULL);

}
