// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: S320240

#include "../ui.h"

void ui_screenInput_screen_init(void)
{
ui_screenInput = lv_obj_create(NULL);
lv_obj_clear_flag( ui_screenInput, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_kbInput = lv_keyboard_create(ui_screenInput);
lv_obj_set_height( ui_kbInput, 120);
lv_obj_set_width( ui_kbInput, lv_pct(100));
//lv_obj_set_x( ui_kbInput, 0 );
//lv_obj_set_y( ui_kbInput, 0 );
lv_obj_set_align( ui_kbInput, LV_ALIGN_BOTTOM_MID );

ui_lbInputLabel = lv_label_create(ui_screenInput);
lv_obj_set_width( ui_lbInputLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lbInputLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lbInputLabel, -111 );
lv_obj_set_y( ui_lbInputLabel, -86 );
lv_obj_set_align( ui_lbInputLabel, LV_ALIGN_CENTER );
lv_obj_set_style_text_align(ui_lbInputLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_taInput = lv_textarea_create(ui_screenInput);
lv_obj_set_width( ui_taInput, 257);
lv_obj_set_height( ui_taInput, 36);
lv_obj_set_x( ui_taInput, 0 );
lv_obj_set_y( ui_taInput, -42 );
lv_obj_set_align( ui_taInput, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_taInput,"Placeholder...");



lv_keyboard_set_textarea(ui_kbInput,ui_taInput);
lv_obj_add_event_cb(ui_kbInput, ui_event_kbInput, LV_EVENT_ALL, NULL);

}
